- hosts: "{{ variable_host | default('mysite') }}"

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      become: true

    - name: Start nginx
      service:
        name: nginx
        state: started
      become: true

    - name: Generate nginx config
      template:
        src: files/nginx.j2
        dest: /etc/nginx/sites-available/mysite
      become: true

    - name: Remove default nginx site from enabled
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
      notify: nginx reload
      become: true

    - name: Create symlink in sites-enabled
      file: src=/etc/nginx/sites-available/mysite dest=/etc/nginx/sites-enabled/mysite state=link
      notify: nginx reload
      become: true

    - name: Add certbot ppa
      apt_repository:
        repo: ppa:certbot/certbot
      become: true

    - name: Install certbox nginx package
      apt:
        name: "python-certbot-nginx"
        state: latest
      become: true

    - name: Remind to issue certificates
      debug:
        msg: "certbot --nginx -d {{fqdn}} -d www.{{fqdn}}"
      when: fqdn | length > 0

  handlers:
    - name: nginx reload
      service:
        name: nginx
        state: restarted
      become: true
